### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by unphased** [ralphbean/ansi2html#58]
Seems like stuff is being encoded to ASCII right now so all my unicode is being trashed. 

Is there a good reason for this?

**Comment by ralphbean** [comment]
Nope.  Let's do utf-8!

**Comment by ralphbean** [comment]
Have you tried the ``--output-encoding=ENCODING`` option?

**Comment by unphased** [comment]
Okay I'll try that. Damn you got back to me fast.

**Comment by unphased** [comment]
Looks like the default is already utf-8 for both input and output encoding. I am using the Python api btw, and it does look to be quite straightforward. Let me find a reproducible example first

**Comment by unphased** [comment]
Sweet. There was no real issue, and it already works great. It was my own code doing encoding to ascii that was doing the stripping. My bad. Awesome tool you got here.

**Comment by ralphbean** [comment]
Awesome awesome!  Enjoy!  :)
