### ISSUE TITLE
updated lines not rendered correctly

### ISSUE THREAD

**Issue by dsummersl** [ralphbean/ansi2html#59]
I'm not totally sure why but this file I have doesn't render correctly:

https://gist.github.com/dsummersl/6a3724d554d487eec796

**Comment by ralphbean** [comment]
I don't think I'm getting the correct data out of gist [here](https://gist.githubusercontent.com/dsummersl/6a3724d554d487eec796/raw/7f38df0b3b92ce8fc6bc42b1494d8776c07228c6/8882.txt).  Can you submit this as a patch adding it as a test case for the test suite?

**Comment by ralphbean** [comment]
OK, not much I can do here without being able to reproduce it.  Thanks for reporting!
