### ISSUE TITLE
1.0.7 release on pypi has stray pyc files preventing stdeb build

### ISSUE THREAD

**Issue by fastcat** [ralphbean/ansi2html#63]
The 1.0.7 source tarball release on pypi contains `./tests/__pycache__/test_ansi2html.cpython-33.pyc`, which causes attempts to build using stdeb to fail.

**Comment by ralphbean** [comment]
Thanks.  A patch to ``MANIFEST.in`` would probably fix this, no?

**Comment by fastcat** [comment]
TBH, I'm not all that familiar with how the python packaging system works.  I think this may just have been human error when preparing the release tarball to upload, since I was able to work around this problem by fetching the git tag and generating my own source tarball via `setup.py sdist`, and then doing the stdeb build against that.

**Comment by posativ** [comment]
You can use `recursive-exclude tests *.pyc`
