### ISSUE TITLE
Can't install from CentOS

### ISSUE THREAD

**Issue by dleviathan** [ralphbean/ansi2html#70]
I use centos 7, when I try install i had error:

> sudo yum install ansi2html
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
> * base: ftp.riken.jp
> * epel: ftp.riken.jp
> * extras: ftp.riken.jp
> * updates: ftp.riken.jp
> No package ansi2html available.
> Error: Nothing to do

**Comment by ralphbean** [comment]
The package is called `python-ansi2html`, but it is not packaged for EPEL7 or CentOS:  https://apps.fedoraproject.org/packages/python-ansi2html
