### ISSUE TITLE
Linkify outputs incorrect results, eats up all my memory

### ISSUE THREAD

**Issue by josephharrington** [ralphbean/ansi2html#76]
There are significant issues with linkification if passed input containing two or more occurrences of the same URL. Even worse, if the input has many occurrences of the same URL it can easily eat up all memory on the system! 🙀

```python
>>> from ansi2html import Ansi2HTMLConverter
>>> converter = Ansi2HTMLConverter(linkify=True)
>>> s = 'http://www.github.com   http://www.github.com'
>>> converter.convert(s, full=False)
'<a href="<a href="http://www.github.com">http://www.github.com</a>"><a href="http://www.github.com">http://www.github.com</a></a>   <a href="<a href="http://www.github.com">http://www.github.com</a>"><a href="http://www.github.com">http://www.github.com</a></a>'
```
Note the incorrectly nested `<a href="<a href=`. This example shows that an input with two occurrences of a URL creates incorrect output with eight occurrences of the same URL. 

The exponential expansion can quickly cause memory issues. The following code uses over 16gb of memory!
```python
>>> s = '\n'.join(['http://www.github.com'] * 30)
>>> converter.convert(s, full=False)
```

There are also issues if one URL is a substring of the other:
```python
>>> s = '''
... http://www.github.com/ralphbean/ansi2html
... http://www.github.com
... '''
>>> print(converter.convert(s, full=False))

<a href="<a href="http://www.github.com">http://www.github.com</a>/ralphbean/ansi2html"><a href="http://www.github.com">http://www.github.com</a>/ralphbean/ansi2html</a>
<a href="http://www.github.com">http://www.github.com</a>
```

**Comment by normanr** [comment]
Also text like: "here is a url -->https://github.com/ralphbean/ansi2html/search?utf8=%E2%9C%93&q=ansi2html&type=<-- that you can click" will not be converted correctly.
