### ISSUE TITLE
colors are lost during conversion

### ISSUE THREAD

**Issue by ssbarnea** [ralphbean/ansi2html#89]
Some colors are during conversion made by ansi2html as the terminal output looks very different than the produced html file.
```
#!/usr/bin/env bash
echo -e "\x1B[31m foobar \x1B[0m"
echo -e "\x1B[32m foobar \x1B[0m"
echo -e "\x1B[96m foobar \x1B[0m"
echo -e "\x1B[01;96m foobar \x1B[0m"
echo -e "\x1B[01;95m foobar \x1B[0m"
echo -e "\x1B[01;94m foobar \x1B[0m"
echo -e "\x1B[01;93m foobar \x1B[0m"
echo -e "\x1B[01;91m foobar \x1B[0m"
echo -e "\x1B[01;90m foobar \x1B[0m"
echo -e "\x1B[01;89m foobar \x1B[0m"
echo -e "\x1B[01;36m foobar \x1B[0m"
```
<img width="461" alt="180810-tripleo-quickstart master" src="https://user-images.githubusercontent.com/102495/43977538-6a074cca-9cdc-11e8-91c3-c635973de14b.png">
<img width="99" alt="aa" src="https://user-images.githubusercontent.com/102495/43977539-6a2590e0-9cdc-11e8-9ee7-6b143ed9f9c0.png">

**Comment by ralphbean** [comment]
Looks like this was fixed by #90.  :)
