### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by hartwork** [ralphbean/ansi2html#91]
Hi!

Latest release 1.5.1 specifies in `setup.py`:
```
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.6",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.1",
        "Programming Language :: Python :: 3.2",
        "Programming Language :: Python :: 3.3",
```
`.travis.yml` tests against:
```
python:
 - "2.7"
 - "3.5"
 - "3.6"
```
It would be tool to get them in sync, support for Python 3.7 added, leftovers of 2.6 and 3.{1..4} be dropped, and supported versions documented in `README.rst` as well. Thank you!

**Comment by ralphbean** [comment]
Updated in https://github.com/ralphbean/ansi2html/commit/5688d50aee39657ab1c18d441e8e65ad82399068

Thanks for pointing it out.  :)

**Comment by hartwork** [comment]
No 3.7? :disappointed: Still, thanks! :smile:

**Comment by ralphbean** [comment]
I didn't see it in the travis docs.  Is it there?

**Comment by hartwork** [comment]
https://github.com/travis-ci/travis-ci/issues/9815 does not look too good but maybe https://github.com/deadsnakes/travis-ci-python3.7-example#update-2018-07-03 works.
